# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hcloud < Formula
  desc ""
  homepage "https://github.com/moovit-sp-gmbh/hcloud-api-client"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/moovit-sp-gmbh/hcloud-api-client/releases/download/v0.0.8/hcloud_0.0.8_darwin_arm64.tar.gz"
      sha256 "382ff5a1e2953618dcf6bb933a5f5a7d7d329f4d32e7fc612615385e32d76b08"

      def install
        bin.install "hcloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moovit-sp-gmbh/hcloud-api-client/releases/download/v0.0.8/hcloud_0.0.8_darwin_amd64.tar.gz"
      sha256 "038dc1518fe7c18eadf46b4983a91a226b0fcc9b583327246ac623a1a8b40d08"

      def install
        bin.install "hcloud"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/moovit-sp-gmbh/hcloud-api-client/releases/download/v0.0.8/hcloud_0.0.8_linux_arm64.tar.gz"
      sha256 "43086054f9e8f759eb639ea1bedc8f6e1054f9ae344d9a58a5de0f335fe12f82"

      def install
        bin.install "hcloud"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/moovit-sp-gmbh/hcloud-api-client/releases/download/v0.0.8/hcloud_0.0.8_linux_amd64.tar.gz"
      sha256 "d78e81e2428e1e42b4f5d9eab20c58af608b28c744193ecf99fbc2b10d14a3c8"

      def install
        bin.install "hcloud"
      end
    end
  end
end
